baseURL = "http://gadogadobnb.com/"
languageCode = "en-us"
title = "Gado-Gado BnB, Yogyakarta"
theme = "accessible-minimalism"
disableHugoGeneratorInject = true
enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
#  [[menu.main]]
#    name = "Posts"
#    url = "/posts/"
#    weight = 2
